# Generated by Django 4.1.7 on 2023-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
    ]
